version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: gym-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: gymdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - gym-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gym-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gym-network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gym-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/gymdb?authSource=admin
      RABBITMQ_URI: amqp://admin:password123@rabbitmq:5672
      NODE_ENV: production
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - gym-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gym-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - gym-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  gym-network:
    driver: bridge